image:
  file: .gitpod.Dockerfile

tasks:
  - name: spring-data-cassandra
    init: |
      cd todobackend-springdata && mvn clean package install -Dmaven.test.skip=true
ports:
  - port: 8080
    onOpen: open-browser 

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - redhat.java
    - github.vscode-pull-request-github
    - gabrielbb.vscode-lombok
    - pivotal.vscode-spring-boot
