image:
  file: .gitpod.Dockerfile

tasks:
  - name: build-sdk
    before: git clone https://github.com/datastax/astra-sdk-java.git
    init: |
      cd /workspace/workshop-spring-stargate/astra-sdk-java &&   mvn clean install -Dmaven.test.skip=true
  - name: build-stargate
    init: |
      cd /workspace/workshop-spring-stargate/stargate-demo && mvn clean package install -Dmaven.test.skip=true
  - name: Open Welcome File
    command: |
      WelcomeFile='/workspace/workshop-spring-stargate/README.md'
      # gp open won't work until the IDE GUI is ready
      until gp open ${WelcomeFile}; do sleep 1; done
      # Safe to open more files from now on
      gp open '/workspace/workshop-spring-stargate/stargate-demo/src/main/resources/application.yml'
ports: 
  - port: 8080
    onOpen: open-browser 

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - redhat.java
    - github.vscode-pull-request-github
    - gabrielbb.vscode-lombok
    - pivotal.vscode-spring-boot
