version: "3.8"
services:

  # Latest version of Cassandra GA
  cassandra3:
    image: cassandra:3.11.8
    ports:
      - 7000:7000
      - 9042:9042
    ulimits:
      memlock: -1

  #cassandra4:
  #   image: cassandra:4.0-beta2
  #   ports:
  #    - 7000:7000
  #    - 9042:9042
  #  ulimits:
  #    memlock: -1

  # Stargate plugged to Cassandra

  
  # docker exec -it `docker ps | grep cassandra:3.11.7 | cut -b 1-12` cqlsh -e "create keyspace petclinic WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };"
  # docker exec -it `docker ps | grep cassandra:3.11.7 | cut -b 1-12` cqlsh -e "describe keyspaces"
  
   