
server:
  port: ${PORT:8080}
 
spring:
   messages:
    basename: i18n/messages  
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  show-actuator: false
  group-configs:
    - group: Rest Controllers (Spring MVC)
      packages-to-scan: com.datastax.demo.stargate
      
# Properties exoected by the starter
astra:
  # Credentials to DB
  client-id: 
  client-secret: 
  application-token: AstraCS:cNzNxcWvlMKUHfzsEJkarzZM:cf3973c149dc67bb99bd17eafe8ecbd7951cf78af002a64415524c58a9df7eac
  # Select an instance
  cloud-region: eu-central-1
  database-id: 500c4934-7da3-47fb-b193-9dccc4375a41
  keyspace: bootiful
  

