
server:
  port: ${PORT:8080}
 
spring:
   messages:
    basename: i18n/messages  
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  show-actuator: false
  group-configs:
    - group: Rest Controllers (Spring MVC)
      packages-to-scan: com.datastax.demo.stargate
      
# Properties exoected by the starter
astra:

  # Credentials to DB
  client-id: KTKniowBHBCISNNfKXCmNmHD
  client-secret: XSrP3CbE0gOibZljTJspXTZ7D-Gpe-z,IoXA1xl_YCBzvbChLq6xu7kr5JoKy9iuvQlEkaSou8_cG-2wUUWc5M1Ze7ZcjE-mbgY_vx0+NuZb8ZqjzmNH_ajcAZP3K5_U
  application-token: AstraCS:KTKniowBHBCISNNfKXCmNmHD:50b5038dcb38f9bf6caaca40815ab06f46251f2e8f54500e8412f7b893452b90

  # Select an instance
  cloud-region: eu-central-1
  database-id: 3c7fc647-c03b-4a0c-aa6b-a00dd677ac53
  keyspace: stargate
  

