
server:
  port: ${PORT:8080}

logging:
  level:
    root: WARN
    com.datastax.demo: INFO
    com.datastax.astra: INFO
    com.datastax.stargate: INFO
    com.datastax.oss: ERROR
    org.junit.vintage: ERROR

spring:
  messages:
    basename: i18n/messages
  thymeleaf:
    mode: XHTML
    prefix: classpath:views/view-
    suffix: .html
  jackson:
    default-property-inclusion: non-null
     
springdoc:
  api-docs:
    enabled: true
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  show-actuator: false
  group-configs:
    - group: Rest Controllers (Spring MVC)
      packages-to-scan: com.datastax.demo.stargate
      
# Properties exopected by the starter
astra:

  # Credentials to DB
  client-id: DHGxwINMpDRIxjaKIMBxIBAL
  client-secret: rfE-YiNbNKZbnUtj3nI6BBEsaQP9W-HlFG,pJvqhoRTXe91QnyOT4c5CE0XZsA,qab-KTU,Sm4sTOzcDZhf+UdzkJZGx+TMEodT1ucmN.G_H7H-UttPDIHZqjJMKpQg6
  application-token: AstraCS:DHGxwINMpDRIxjaKIMBxIBAL:951492684a43817978bf5932439e48fa2f71884fd23539df644387b980ca762e

  # Select an instance
  cloud-region: us-east-1
  database-id: 58a2e502-fccf-4524-ac22-e59277e63edc
  keyspace: stargate 
